# Generated by Django 3.0.3 on 2020-02-20 15:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('westPointInfo', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='graduationyear',
            old_name='cadetCompany_text',
            new_name='graduationYear_text',
        ),
    ]
